# Generated by Django 4.2.6 on 2024-02-12 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('id_proof_image', models.ImageField(blank=True, null=True, upload_to='id_proof_images/')),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_certificate_1', models.FileField(blank=True, null=True, upload_to='pdf_certificates/')),
                ('pdf_certificate_2', models.FileField(blank=True, null=True, upload_to='pdf_certificates/')),
                ('pdf_certificate_3', models.FileField(blank=True, null=True, upload_to='pdf_certificates/')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
