# Generated by Django 4.2.6 on 2024-02-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0007_doctorleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('hospital', 'Hospital Method'), ('online', 'Online Method')], max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skin_app.appointment')),
            ],
        ),
    ]
