# Generated by Django 4.2.6 on 2024-02-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0009_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ImageField(upload_to='brand_logos/')),
                ('brand_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_phone', models.CharField(max_length=15)),
                ('brand_license', models.FileField(upload_to='brand_licenses/')),
            ],
        ),
    ]
