# Generated by Django 4.2.6 on 2024-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0011_alter_brand_brand_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_license',
            field=models.FileField(default='default_license.pdf', upload_to='brand_licenses/'),
        ),
    ]
