# Generated by Django 4.2.6 on 2024-02-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0012_alter_brand_brand_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
