# Generated by Django 4.2.6 on 2024-02-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0015_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
