# Generated by Django 4.2.6 on 2024-02-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0018_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20),
        ),
    ]
