# Generated by Django 4.2.6 on 2024-02-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0019_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='assets/img/product_default.png', upload_to='products/'),
        ),
    ]
