# Generated by Django 4.2.6 on 2024-02-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0021_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
