# Generated by Django 4.2.6 on 2024-02-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0023_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
