# Generated by Django 4.2.6 on 2024-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0027_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
