# Generated by Django 4.2.6 on 2024-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0036_product_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_limit',
            field=models.CharField(choices=[('above_10', 'Above 10'), ('below_5', 'Below 5'), ('above_18', 'Above 18'), ('above_15', 'Above 15'), ('below_12', 'Below 12'), ('above_21', 'Above 21')], default=True, max_length=50),
        ),
    ]
