# Generated by Django 4.2.6 on 2024-02-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0040_ingredient_remove_product_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
