# Generated by Django 4.2.6 on 2024-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0041_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
