# Generated by Django 4.2.6 on 2024-03-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0042_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='skin_app.ingredient'),
        ),
    ]
