# Generated by Django 4.2.6 on 2024-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0044_remove_product_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default=True),
        ),
    ]
