# Generated by Django 4.2.6 on 2024-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0045_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_concern',
            field=models.CharField(blank=True, choices=[('Acne', 'Acne'), ('Aging', 'Aging'), ('Dryness', 'Dryness'), ('Oiliness', 'Oiliness'), ('Sensitivity', 'Sensitivity')], max_length=50, null=True),
        ),
    ]
