# Generated by Django 4.2.6 on 2024-03-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0048_remove_product_skin_concern_product_skin_concerns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_concerns',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_type',
        ),
        migrations.DeleteModel(
            name='SkinConcern',
        ),
    ]
