# Generated by Django 4.2.6 on 2024-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0049_remove_product_skin_concerns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne')], max_length=50)),
            ],
        ),
    ]
