# Generated by Django 4.2.6 on 2024-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0050_skinconcern'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_concerns',
            field=models.ManyToManyField(blank=True, to='skin_app.skinconcern'),
        ),
    ]
