# Generated by Django 4.2.6 on 2024-03-02 09:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0051_product_skin_concerns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_concerns',
        ),
        migrations.AddField(
            model_name='product',
            name='skin_concerns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne')], default=True, max_length=50),
        ),
    ]
