# Generated by Django 4.2.6 on 2024-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0052_remove_product_skin_concerns_product_skin_concerns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('brightening', 'Brightening'), ('hydrating', 'Hydrating'), ('anti-aging', 'Anti-aging'), ('acne-fighting', 'Acne-fighting')], max_length=50)),
            ],
        ),
    ]
