# Generated by Django 4.2.6 on 2024-03-02 10:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0054_product_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('brightening', 'Brightening'), ('hydrating', 'Hydrating'), ('anti-aging', 'Anti-aging'), ('acne-fighting', 'Acne-fighting')], default=True, max_length=50),
        ),
    ]
