# Generated by Django 4.2.6 on 2024-03-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0056_order_delete_highlight_remove_product_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.product')),
            ],
        ),
    ]
