# Generated by Django 4.2.6 on 2024-03-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0059_userprofile_city_userprofile_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.userprofile')),
            ],
        ),
    ]
