# Generated by Django 4.2.6 on 2024-03-14 03:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0061_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_concerns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne'), ('Eczema', 'Eczema'), ('Wrinkles', 'Wrinkles'), ('Pigmentation', 'Pigmentation'), ('Sun Damage', 'Sun Damage'), ('Dryness', 'Dryness'), ('Dull Skin', 'Dull Skin'), ('Dark Circles', 'Dark Circles'), ('Age spots', 'Age spots'), ('Acne Scars', 'Acne Scars')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skinconcern',
            name='name',
            field=models.CharField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne'), ('Eczema', 'Eczema'), ('Wrinkles', 'Wrinkles'), ('Pigmentation', 'Pigmentation'), ('Sun Damage', 'Sun Damage'), ('Dryness', 'Dryness'), ('Dull Skin', 'Dull Skin'), ('Dark Circles', 'Dark Circles'), ('Age spots', 'Age spots'), ('Acne Scars', 'Acne Scars')], max_length=50),
        ),
    ]
