# Generated by Django 4.2.6 on 2024-03-14 04:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0062_product_highlights_alter_product_skin_concerns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('mature', 'Mature')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_concerns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne'), ('Eczema', 'Eczema'), ('Wrinkles', 'Wrinkles'), ('Pigmentation', 'Pigmentation'), ('Sun Damage', 'Sun Damage'), ('Dryness', 'Dryness'), ('Dull Skin', 'Dull Skin'), ('Dark Circles', 'Dark Circles'), ('Age spots', 'Age spots'), ('Acne Scars', 'Acne Scars'), ('Oily scalp', 'Oily scalp'), ('Dry hair', 'Dry hair'), ('Dandruff', 'Dandruff'), ('Breakage and split ends', 'Breakage and split ends')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skinconcern',
            name='name',
            field=models.CharField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne'), ('Eczema', 'Eczema'), ('Wrinkles', 'Wrinkles'), ('Pigmentation', 'Pigmentation'), ('Sun Damage', 'Sun Damage'), ('Dryness', 'Dryness'), ('Dull Skin', 'Dull Skin'), ('Dark Circles', 'Dark Circles'), ('Age spots', 'Age spots'), ('Acne Scars', 'Acne Scars'), ('Oily scalp', 'Oily scalp'), ('Dry hair', 'Dry hair'), ('Dandruff', 'Dandruff'), ('Breakage and split ends', 'Breakage and split ends')], max_length=50),
        ),
    ]
