# Generated by Django 4.2.6 on 2024-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0063_product_skin_type_alter_product_skin_concerns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('mature', 'Mature'), ('all skintype', 'all skintype')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='skinconcern',
            name='name',
            field=models.CharField(choices=[('dryness', 'Dryness'), ('oiliness', 'Oiliness'), ('sensitivity', 'Sensitivity'), ('acne', 'Acne'), ('Eczema', 'Eczema'), ('Wrinkles', 'Wrinkles'), ('Pigmentation', 'Pigmentation'), ('Sun Damage', 'Sun Damage'), ('Dryness', 'Dryness'), ('Dull Skin', 'Dull Skin'), ('Dark Circles', 'Dark Circles'), ('Age spots', 'Age spots'), ('Acne Scars', 'Acne Scars'), ('Oily scalp', 'Oily scalp'), ('Dry hair', 'Dry hair'), ('Dandruff', 'Dandruff'), ('Breakage and split ends', 'Breakage and split ends')], max_length=200),
        ),
    ]
