# Generated by Django 4.2.6 on 2024-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0065_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
