# Generated by Django 4.2.6 on 2024-03-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0068_prescription_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.subcategory'),
        ),
    ]
