# Generated by Django 4.2.6 on 2024-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0069_alter_prescription_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='subcategory',
        ),
    ]
