# Generated by Django 4.2.6 on 2024-04-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0070_remove_prescription_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skin_corner', models.CharField(choices=[('Round', 'Round'), ('Square', 'Square'), ('Oval', 'Oval')], max_length=10)),
                ('procedure', models.TextField()),
                ('post_procedure', models.TextField()),
                ('highlights', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
