# Generated by Django 4.2.6 on 2024-04-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0071_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
