# Generated by Django 4.2.6 on 2024-04-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0072_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('procedure', models.TextField()),
                ('post_procedure', models.TextField()),
                ('highlights', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.category')),
            ],
        ),
    ]
