# Generated by Django 4.2.6 on 2024-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0073_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
