# Generated by Django 4.2.6 on 2024-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0074_prescription_advice_prescription_follow_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
