# Generated by Django 4.2.6 on 2024-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0077_prescription_is_service_suggested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_service_suggested',
        ),
    ]
