# Generated by Django 4.2.6 on 2024-04-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0078_remove_prescription_is_service_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skin_app.service'),
        ),
    ]
