# Generated by Django 4.2.6 on 2024-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0079_prescription_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='service',
        ),
    ]
