# Generated by Django 4.2.6 on 2024-04-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0080_remove_prescription_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_services', to='skin_app.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin_app.service')),
            ],
        ),
    ]
