# Generated by Django 4.2.6 on 2024-04-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0082_alter_servicesuggest_service_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
    ]
