# Generated by Django 4.2.6 on 2024-04-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0085_alter_booking_time_slot_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
