# Generated by Django 4.2.6 on 2024-04-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0091_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
