# Generated by Django 4.2.6 on 2024-04-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0092_remove_message_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
    ]
